words/urls.py
from django.urls import path

from . import views




app_name = 'words'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<str:question_key>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<str:question_key>/submit/', views.submit, name='submit'),
]

wordsProject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('words.urls')),
    #path('words/', include('words.urls')),
    path('admin/', admin.site.urls),
]

words/models.py
from django.db import models

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=400)
    image_text = models.CharField(max_length=50)
    question_key = models.CharField(max_length=200)
    answer_text = models.CharField(max_length=200)
    def __str__(self):
        return self.question_text
    # def get(self):
    #     return self.question_text

words/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic

from .models import Question
# Create your views here.
class IndexView(generic.ListView):
    model = Question
    template_name = 'words/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('id')[:5]

class DetailView(generic.DetailView):
    model = Question
    slug_field = 'question_key'
    template_name = 'words/detail.html'
    def get_object(self):
        object = get_object_or_404(Question,question_key=self.kwargs['question_key'])
        return object

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'words/results.html'

def submit(request, question_key):
    question = get_object_or_404(Question, pk=question_key)
    try:
        answer_from_post = (request.POST['answerSubmit'])
        if answer_from_post == '':
            raise TypeError
        elif answer_from_post != question.answer_text:    
            return render(request, 'words/detail.html', {
                'question': question,
                'error_message': "Sorry bud, wrong answer...",
            })
    except (TypeError):
        #Redisplay the question voting form.
        return render(request, 'words/detail.html', {
                'question': question,
                'error_message': "At least try something... Ugh...",
            })
        #return HttpResponseRedirect(reverse('words:detail', args=(question.question_key,)))
    else:
        # print(question.id)
        next_question_id = question.id + 1
        next_question = get_object_or_404(Question, pk=next_question_id)
        if question.answer_text == answer_from_post:
            return HttpResponseRedirect(reverse('words:detail', args=(next_question.question_key,)))
            # return render(request, 'words/detail.html', {
            # 'question': question,
            # 'congrats_message': "Correct!",
            # })  
        # question.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.        

words/templates/words/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Words To Know</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'words/css/style.css' %}">   
</head>
<script>
    document.oncontextmenu = new Function("return false;");
</script>
<body>
    <header>
        <!-- <div class="container">
            <div class="row">
                <div class="col-md-12 logo">
                    <figure>
                        <img src="{% static 'words/images/' %}{{question.image_text}}" alt="{{ question.question_text }}" class="img-fluid">
                    </figure>
                </div>
            </div>
        </div> -->
    </header>
    <main>
        <div class="container">
            <div class="row">
                <div class="col-md-12 question_body">
                    <form action="{% url 'words:submit' question.id %}" method="post">
                    {% csrf_token %}
                        <h1>{{ question.question_text }}</h1>
                        <input type="input" name="answerSubmit" placeholder="Your Answer..." id="answer{{question.id}}">
                        <input type="submit" value="Submit">
                        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
                    </form>
                </div>
            </div>
        </div>
    </main>
    <footer>

    </footer>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

words/templates/words/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Words To Know</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'words/css/style.css' %}">   
</head>
<script>
    document.oncontextmenu = new Function("return false;");
</script>
<body>
    <header>
        <!-- <div class="container">
            <div class="row">
                <div class="col-md-12 logo">
                    <figure>
                        <img src="{% static 'words/images/' %}resim.png" alt="wordstoknow" class="img-fluid">
                    </figure>
                </div>
            </div>
        </div> -->
    </header>
    <main>
        <div class="container">
            <div class="row">
                <div class="col-md-12 question_body main">
                    <a href="{% url 'words:detail' 'youwillneverknow' %}" class="mainmenu">
                        WORDS<br>TO<br>KNOW<br>
                        <small>powered by&nbsp;<img src="{% static 'words/images/' %}resim.png" alt="wordstoknow" class="img-fluid">
                        </small>
                    </a>
                </div>
            </div>
        </div>
    </main>
    <footer>

    </footer>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

words/templates/words/results.html
<h1>{{ question.answer_text }}</h1>

<a href="{% url 'words:detail' question.id %}">Vote again?</a>